using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CloseMenuAcheo : MonoBehaviour {

	DropCube dc;
	SanityGestion SG;

	public GameObject MainCamera;
	public GameObject Cam2;
	public GameObject artefactArcheo;

	// Use this for initialization
	void Start () {
		dc = GameObject.Find ("Player").GetComponent<DropCube>();
		SG = GameObject.Find ("Player").GetComponent<SanityGestion>();
	}
	
	// Update is called once per frame
	void Update ()
	{
		if (Input.GetButtonDown ("dropcube")  && dc.isCubeOnGround) {
			SG.sanity = 1;
			MainCamera.SetActive (true);
			Cam2.SetActive (false);
			artefactArcheo.SetActive (false);
			dc.StartCoroutine ("returnCubeBool");
		}
	}
}
